name: Pryv HealthKit bridge

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
     
jobs:
  test:

    runs-on: macOS-latest
    
    strategy:
      matrix:
        xcode: ['/Applications/Xcode_11.1.app/Contents/Developer']

    steps:
    - name: Download master branch
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        pod install
      shell: bash
      env:
        DEVELOPER_DIR: ${{ matrix.xcode }}
        
    - name: Build and test
      run: |
        gem install slather
        xcodebuild -enableCodeCoverage YES -scheme HealthKitBridge -workspace HealthKitBridge.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest' clean test
        slather
        bash <(curl -s https://codecov.io/bash) -f ./cobertura.xml
      env:
       destination: ${{ matrix.destination }}
